# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=64)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('art', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.TextField()),
                ('genre', models.CharField(max_length=128)),
                ('song_length', models.PositiveIntegerField(default=0, null=True)),
                ('lyrics', models.TextField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
        ),
    ]
