# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171105_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='music_entry',
            new_name='MusicEntry',
        ),
        migrations.RenameModel(
            old_name='music_playlist',
            new_name='MusicPlaylist',
        ),
        migrations.RenameModel(
            old_name='user_account',
            new_name='UserAccount',
        ),
    ]
